#spring.application.name=InsuranceApplication
temporal:
    serviceAddress: 'localhost:8233'
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/InsuranceApp
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
